[package]
name = "rsmack-seanum"
version = "0.15.0"
edition = "2021"
description = "Enhanced documentation macro with constant evaluation"
license = "MIT"
[lib]
proc-macro = true
[dependencies]
darling = "0.21.0"
proc-macro-error2 = "2.0.1"
proc-macro2 = "1.0.92"
quote = "1.0.37"
rsmack-utils = { version = "0.15.0", path = "../rsmack-utils" }
syn = { version = "2.0.90", features = ["full"] }
rsmack-megamac = { version = "0.15.0", path = "../rsmack-megamac" }
const_format = "0.2.33"
serde = { version = "1", features = ["derive"] }
fake = { version = "4", features = ["derive"] }
sea-orm-migration={version = "1.1.0"}
[lints]
workspace = true
