[package]
name = "rsmack-megamac"
version = "0.13.0"
edition = "2021"
description = "Procedural macro generator with automatic documentation and error handling"
license = "MIT"
[lib]
proc-macro = true
[dependencies]
darling = "0.21.0"
proc-macro-error2 = "2.0.1"
proc-macro2 = "1.0.92"
quote = "1.0.37"
rsmack-utils = { version = "0.13.0", path = "../rsmack-utils" }
syn = { version = "2.0.90", features = ["full"] }
strum = { version = "0.27.0", features = ["derive"] }
bon = "3.2.0"
indoc = "2.0.5"
stringcase = "0.4"
[lints]
workspace = true
