[package]
name = "rsmack-utils"
version = "0.0.0"
edition = "2021"
[dependencies]
darling = "0.20.10"
proc-macro-error = "1.0.4"
proc-macro2 = "1.0.92"
quote = "1.0.37"
syn = { version = "2.0.90", features = ["full"] }
