[package]
name = "rsmack-utils"
version = "0.0.0"
edition = "2021"
[dependencies]
darling = "0.20.10"
proc-macro-error2 = "2.0.1"
proc-macro2 = "1.0.92"
quote = "1.0.37"
syn = { version = "2.0.90", features = ["full"] }
build-print = "0.1.1"
stringcase = "0.3"
bon = "3.2.0"
