[package]
name = "rsmack-fs"
version = "0.3.0"
edition = "2021"
[lib]
proc-macro = true
[dependencies]
darling = "0.20.10"
proc-macro-error2 = "2.0.1"
proc-macro2 = "1.0.92"
quote = "1.0.37"
rsmack-utils = { path = "../rsmack-utils" }
rsmack-megamac = { path = "../rsmack-megamac" }
syn = { version = "2.0.90", features = ["full"] }
run_script = "0.11.0"
[lints]
workspace = true
