[package]
name = "rsmack-fs"
version = "0.0.0"
edition = "2021"
[lib]
proc-macro = true
[dependencies]
darling = "0.20.10"
proc-macro-error = "1.0.4"
proc-macro2 = "1.0.92"
quote = "1.0.37"
rsmack-utils = { path = "../rsmack-utils" }
syn = { version = "2.0.90", features = ["full"] }
paste = { git = "https://github.com/elcoosp/paste", branch = "feat/dash" }
run_script = "0.11.0"
